### ISSUE TITLE
Can the input of test GW_OPENSHELL be modified to give ionization potential?

### ISSUE THREAD

**Issue by xiongyan21** [NWChem/input-generator#1]
The compiled 7.2.0 on Ubuntu18.04, python2.7, LAPACK， openmpi and GCC7.5.0 gives     
Alpha Orbitals
          State     Energy (eV)     Error (eV)
          -----------------------------------
@GW         8        -13.237           0.001
@GW         9        -12.542           0.000
@GW        10        -12.360           0.000
@GW        11         -9.991           0.000
@GW        12         -7.780           0.001
@GW        13          3.732           0.000
@GW        14          3.851           0.000
@GW        15          5.314           0.000
@GW        16          9.843           0.001
@GW        17         11.907           0.000

                   Beta Orbitals
          State     Energy (eV)     Error (eV)
          -----------------------------------
@GW         7        -16.569           0.000
@GW         8        -14.089           0.000
@GW         9        -12.853           0.000
@GW        10        -11.113           0.000
@GW        11         -9.813           0.000
@GW        12          0.782           0.000
@GW        13          4.374           0.000
@GW        14          4.112           0.000
@GW        15          5.494           0.000
@GW        16         10.421           0.000
 
The accompanied gives
           Alpha Orbitals
          State     Energy (eV)     Error (eV)
          -----------------------------------
@GW         8        -13.237           0.001
@GW         9        -12.542           0.000
@GW        10        -12.360           0.000
@GW        11         -9.991           0.000
@GW        12         -7.780           0.001
@GW        13          3.732           0.000
@GW        14          3.851           0.000
@GW        15          5.314           0.000
@GW        16          9.843           0.001
@GW        17         11.907           0.000

                   Beta Orbitals
          State     Energy (eV)     Error (eV)
          -----------------------------------
@GW         7        -16.569           0.000
@GW         8        -14.089           0.000
@GW         9        -12.853           0.000
@GW        10        -11.113           0.000
@GW        11         -9.813           0.000
@GW        12          0.782           0.000
@GW        13          4.374           0.000
@GW        14          4.112           0.000
@GW        15          5.494           0.000
@GW        16         10.421           0.000

Can the input of tit  be modified to give ionization potential?

Very Best Regards!

**Comment by xiongyan21** [comment]
I have found an example in the manual, but the following error appears
 Summary of "ao basis" -> "" (spherical)
 ------------------------------------------------------------------------------
       Tag                 Description            Shells   Functions and Types
 ---------------- ------------------------------  ------  ---------------------
 h                          def2-svp                 3        5   2s1p
 o                          def2-svp                 6       14   3s2p1d


 Attempting to read a basis set from a  non-existing file:
 /home/hp/computation/nwchem7.2.0/src/basis/libraries/def2-universal-jkfit                                                                                                                                                                                      
 ------------------------------------------------------------------------
 bas_tag_lib: failed opening basis file                   0
 ------------------------------------------------------------------------
 input error at line   12: at end of line looking for character string
 h library def2-universal-jkfit
 ------------------------------------------------------------------------
  current input line : 
    12: h library def2-universal-jkfit
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 There is an error in the specified basis set
 ------------------------------------------------------------------------

How to use this basis sets.

Very Best Regards!

**Comment by jeffhammond** [comment]
Please create this issue against https://github.com/nwchemgit/nwchem.  It has nothing to do with my input file generator script.

**Comment by xiongyan21** [comment]
Thanks!
It didn't converge, either.
...
@GW        12          6.551           0.000
@GW        13          8.381           0.000
@GW        14         10.017           0.000
@GW        15          9.953           0.009 *

  * Result did not converge

It seems I cannot post on that net for a long time. 
I will try.

Very Best Regards!
